baseURL = "https://globaloong.pages.dev"
languageCode = "zh-cn"
title = "全球头条"
theme = "hugo-coder"
defaultContentLanguage = "zh"

[pagination]
  pageSize = 10

[params]
  author = "全球头条"
  info = "全球华人新闻资讯平台"
  description = "全球头条 GlobalOong"
  avatarURL = "images/logo-globaloong.png"
  logo = "images/logo-globaloong.png"
