baseURL = "https://dashixiong131313.github.io/"
languageCode = "zh-cn"
title = "全球头条"
theme = "hugo-coder"
defaultContentLanguage = "zh"

[pagination]
  pageSize = 10

[params]
  author = "全球头条"
  info = "全球华人新闻资讯平台"
  description = "全球头条 GlobalOong 新闻平台"
  logo = "/images/logo-globaloong.png"
  publishDir = "public"
[taxonomies]
  category = "categories"
  tag = "tags"
